config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  devise_for :users
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  resources :relations, only: [:new, :create]
  resources :rooms, only: [:new, :create, :edit, :update, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
  end
  get 'messages/:id', to: 'messages#checked'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/relation.rb
class Relation < ApplicationRecord
  has_many :follower, class_name: 'User'
  has_many :following, class_name: 'User'

  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :relations
  has_many :followings, through: :relations
  has_many :followers, through: :relations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  KANA_RAGEX = /\A[ァ-ヶー－]+\z/.freeze
  with_options presence: true do
    validates :family_name
    validates :last_name
    validates :family_name_kana, format: {with: KANA_RAGEX}
    validates :last_name_kana, format: {with: KANA_RAGEX}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :last_name, :family_name_kana, :last_name_kana])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user).order(id: "DESC")
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    message = @room.messages.find(params[:id])
    if message.destroy
      redirect_to room_messages_path(@room)
    end
  end

  def checked
    message = Message.find(params[:id])
    if message.user_id != current_user.id
      if message.checked
        message.update(checked: false)
      else
        message.update(checked: true)
      end
    end
    item = Message.find(params[:id])
    render json: { message: item }
  end

  private

  def message_params
    params.require(:message).permit(:content,:image).merge(user_id: current_user.id)
  end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  def new
    @relation = Relation.new
  end

  def create
    @relation = Relation.new(relation_params) 
    if @relation.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def relation_params
    params.require(:relation).permit(:following_id, :follower_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private
  
  def room_params
    params.require(:room).permit(:name, user_ids:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:family_name, :last_name, :family_name_kana, :last_name_kana)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TalkRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= link_to @room.name, edit_room_path(@room) %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "トーク終了", root_path %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], html: {class: "form"}, local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'トークを投稿できます', maxlength: 255 %>
    <label class="form-image">
      <span class="iamge-file">画像</span>
      <%= f.file_field :image, class: "hidden" %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message"data-id=<%= message.id %> data-check=<%= message.checked %>>
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.family_name + message.user.last_name %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content%>
    </div>
    <%= image_tag message.image.variant(resize: '400x400'), class: 'message-image' if message.image.attached? %>
  </div>
  <% if current_user.id == message.user.id %>
    <div class="delete-btn">
      <%= link_to "削除", room_message_path(@room, message.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.family_name + current_user.last_name, edit_user_path(current_user) %>
  </div>
  <div class="create-room">
    <div class="talk-btn">
      <%= link_to "トークルーム作成", new_room_path %>
      <%= link_to "トーク相手を探す", new_relation_path%>
    </div>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/relations/new.html.erb
<div class="relation-create">
  <h1>トーク相手を探しましょう</h1>
  <%= form_with model: @relation, local: true do|f| %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field'>
        <div class='chat-room-form__field--left'>
          <label class='chat-room-form__label' for='chat_room_チャットメンバー'>トークメンバー</label>
        </div>
        <div class='chat-room-form__field--right'>
          <%= f.collection_select(:follower_id, User.all.where.not(id: current_user.id), :id, :family_name, prompt: "選択してください")%>
          <%= f.hidden_field :following_id, value: current_user.id %>
        </div>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
        <%= link_to "トークルームへ戻る", root_path, class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<div class='chat-room-form'>
  <h2>トークルーム名の修正または削除ができます<h2>
  <%=form_with model: @room, method: :patch, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :トークルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: '新しいトークルーム名を入力してください'%>
      </div>
    </div>
    <div class="btn-field">
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn' %>
      </div>
      <div class="chat-room-form__field">
        <%= link_to "トークルームを削除する", room_path(@room), method: :delete, class: "room-destroy-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
  <div class="first">
    <div class="first-messages">
      <p class="first-message">相手を探して<br>トークを開始しましょう</p>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>相手を選択しトークを開始しましょう</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :トークルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'トークルーム名を20文字以内で入力してください', maxlength: 20%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>トークメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="" >トーク相手を選択してください</option>
          <% User.all.where.not(id: current_user.id).each do |user| %>
              <option value=<%=user.id%>><%= user.family_name + user.last_name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%=current_user.id%>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
        <%= link_to "トークルームへ戻る", root_path, class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class="name-form">
          <div class='field'>
            <div class='field-label'>
              <%= f.label :性%>
            </div>
            <div class='field-input'>
              <%= f.text_field :family_name, autofocus: true %>
            </div>
          </div>
          <div class='field'>
            <div class='field-label'>
              <%= f.label :名%>
            </div>
            <div class='field-input'>
              <%= f.text_field :last_name %>
            </div>
          </div>
        </div>
        <div class="name-form">
          <div class='field'>
            <div class='field-label'>
              <%= f.label :セイ（全角カナ）%>
            </div>
            <div class='field-input'>
              <%= f.text_field :family_name_kana %>
            </div>
          </div>
          <div class='field'>
            <div class='field-label'>
              <%= f.label :メイ（全角カナ）%>
            </div>
            <div class='field-input'>
              <%= f.text_field :last_name_kana %>
            </div>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "更新する", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>